# Generated by Django 2.2 on 2019-09-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='overall',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
